In [3]:
import numpy as np
import pandas as pd

### Creating a DataFrame

In [4]:
data = {
    'Name' : ['John', 'Anna', 'Peter', 'Linda'],
    'Age' : [28, 34, 29, 42],
    'City' : ['New York', 'Paris', 'Berlin', 'London'],
    'Salary' : [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [8]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 75000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

df2 = pd.DataFrame(data_list)
columns = ['Name', 'Age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   75000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### Selections and Indexing of Columns

In [9]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   75000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [18]:
df2['Name']
# print("\n")
# df2['City']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [19]:
df2[['Name', 'City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

### Creating a new Column

In [10]:
df2["Designation"] = ["Doctor", "Engineer", "Doctor", "Engineer"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   75000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

### Removing a Column

In [11]:
df2.drop('Designation', axis = 1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   75000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [46]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   75000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [12]:
df2.drop('Designation', axis=1, inplace=True, errors='ignore')
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   75000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### Removing a Row

In [50]:
df2.drop(0, axis = 0)

    Name  Age    City  Salary
1   Anna   34   Paris   75000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [51]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   75000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### Selecting a Row

In [58]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   75000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [13]:
df2.loc[0]    #Loc -> Location of Row

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [56]:
df2.loc[[0, 1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   75000

In [ ]:
df2.iloc[3]       #iloc -> Location of index

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

### Selecting Subsets of Rows and Columns

In [14]:
df2.loc[[0, 1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   75000

In [62]:
df2.loc[[0, 1]][["City", "Salary"]]

       City  Salary
0  New York   65000
1     Paris   75000

### Conditional Statements

In [15]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   75000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [16]:
# Only want to see those people whose age are is avove 30

df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   75000
3  Linda   42  London   85000

In [19]:
# People whose age is above 30 AND city is Paris
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   75000